### ISSUE TITLE
Custom schemas/refinements

### ISSUE THREAD

**Issue by brettz9** [commonbaseapp/zodex#15]
Just a heads up that I'd hope we could add a mechanism for refinements/customs schemas at some point.

However, I think this would be blocked by https://github.com/colinhacks/zod/issues/2515

**Comment by rebeccaEller** [comment]
Named Superrefinements whould be possible with a functionsdictionary
have tested it on the deserialization branch

looks like that:
![grafik](https://github.com/commonbaseapp/zodex/assets/103248807/530eca70-8f2c-4404-a60d-7f628c3f2edc)

If you are interessed i can make a pull request

**Comment by brettz9** [comment]
> Named Superrefinements whould be possible with a functionsdictionary have tested it on the deserialization branch
> 
> looks like that: ![grafik](https://private-user-images.githubusercontent.com/103248807/321932491-530eca70-8f2c-4404-a60d-7f628c3f2edc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjQ5NTQsIm5iZiI6MTcxNzc2NDY1NCwicGF0aCI6Ii8xMDMyNDg4MDcvMzIxOTMyNDkxLTUzMGVjYTcwLThmMmMtNDQwNC1hNjBkLTdmNjI4YzNmMmVkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxMjUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjY5M2JjMTE4MzcyYmJmMTlhZjhiYjRjOWM4NjQyZDNmZDFkNTQ1N2ZlM2I2Zjg4NGQ5YTk5ODIyYWIxNDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-FQMDJTCe72tEhbxgfG_aDjB7siqxri0JtB3Pg00ywY)
> 
> If you are interessed i can make a pull request

Looks to me to be a very good solution, at least if Zod is not going to support named effects so as to avoid the need for passing options to `zerialize`... I'm curious as to how you're doing the function comparison (function object identity or string comparison)

**Comment by brettz9** [comment]
@rebeccaEller Do you think you could submit a PR?
