### ISSUE TITLE
Switch to JSON

### ISSUE THREAD

**Issue by brettz9** [commonbaseapp/zodex#19]
It appears to me that the Zodex format is JSON-compatible with the exception of the current use of a few `BigInt`'s (`min`, `max`, and `multipleOf` on the `"bigint"` type).

In order to make the format serializable for the network out of the box, perhaps this small deviation from JSON could be changed, using strings to represent the BigInt values?

**Comment by brettz9** [comment]
Seems that version 0.8.0 didn't end up getting published for some reason...

**Comment by Gregoor** [comment]
The token has expired, I just did a manual publish and will update the token
